# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSer', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile', models.FileField(upload_to='')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileuploads', to='AuthSer.User')),
            ],
        ),
    ]
