# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_fileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='datafile',
            new_name='file',
        ),
    ]
