# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSer', '0001_initial'),
        ('chat', '0002_auto_20180209_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='members',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AuthSer.User'),
            preserve_default=False,
        ),
    ]
