# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180217_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='owner',
            new_name='user',
        ),
    ]
