# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180211_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthSer.User', to_field='user_email'),
        ),
    ]
