# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180217_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='user',
        ),
    ]
